version: "3"
networks:
  rede:
    driver: bridge
services:
  database:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - PGSSLMODE=allow
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rede
  app:
    build: .
    environment:
      - "STEMMER_HOST=${STEMMER_HOST}"
      - "STEMMER_PORT=${STEMMER_PORT}"
      - "DATABASE_HOST=${DATABASE_HOST}"
      - "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}"
    networks:
      - rede
    ports:
      - 8080:8080
    depends_on:
      - database
